<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Porto - Homepage 5</title>
		<meta name="description" content="Default Description" />
		<meta name="keywords" content="Magento, Varien, E-commerce" />
		<meta name="robots" content="INDEX,FOLLOW" />
			
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="icon" href="http://newsmartwave.net/magento/porto/skin/frontend/smartwave/porto/favicon.ico" type="image/x-icon" />
		<link rel="shortcut icon" href="http://newsmartwave.net/magento/porto/skin/frontend/smartwave/porto/favicon.ico" type="image/x-icon" />
		
		<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
		<link href='//fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'/>
		
		<link href="<?php echo APP_PATH; ?>/assets/css/reset.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo APP_PATH; ?>/assets/css/main.css" rel="stylesheet" type="text/css" />
			
		<script src='<?php echo APP_PATH; ?>/assets/plugins/jquery-1.11.3.min.js' type='text/javascript'></script>
		<script src='<?php echo APP_PATH; ?>/assets/plugins/jquery.slide.js' type='text/javascript'></script>
			
		<base href="<?php echo BASE_URL; ?>" />
	</head>
	<body>
		<div id="main-wrapper">
			<div id="top-links-container">
       			<div id="top-links" class='wrapper-width container'>
					<div id="top-links-right">
                		<ul class="links">
                        	<li class="first"><a href="#" title="My Account">Minha Conta</a></li>
							<li><a href="#" title="Daily deal">Daily deal</a></li>
							<li><a href="#" title="My Wishlist">My Wishlist</a></li>
							<li><a href="#" title="Blog">Blog</a></li>
							<li class="last"><a href="#" title="Log In">Sair</a></li>
						</ul>
					</div>
					<p class="welcome-msg">Seja bem vindo, Leonardo! </p>
				</div>
				<br clear='all' />
			</div>
			
			<div id="header" class="container wrapper-width">
                <h1 class="logo">
                	<a href="http://newsmartwave.net/magento/porto/index.php/demo5_en/" title="Magento Commerce" class="logo">
                	<img src="http://newsmartwave.net/magento/porto/skin/frontend/smartwave/porto/images/logo.png" alt="Magento Commerce"></a>
				</h1>
                <div class="cart-area">
            		<div class="custom-block">
            			<i class="icon-phone" style="margin-right: 5px;"></i>
            			<span>(+404) 158 14 25 78</span>
            			<span class="split"></span>
            			<a href="#">CONTACT US</a>
					</div>
					<div class="mini-cart">
						<span class="cart-info">
							<span class="cart-qty">0</span>
						</span>
				        <div class="mini-cart-itens-tooltip">
				            <div class="inner-wrapper"><p class='cart-empty'>Você não possuí nenhum produto no seu carrinho.</p> </div>
				        </div>
					</div>
				</div>
				<div id="search-area">
					<a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
					<form id="search_mini_form" action="//newsmartwave.net/magento/porto/index.php/demo5_en/catalogsearch/result/" method="get">
						<div class="form-search ">
							<input id="search" placeholder="Buscar produtos..." type="text" name="q" class="input-text" autocomplete="off">
							<select id="cat" name="cat">
								<option value="">Todas Categorias</option>
							</select>
							<button type="submit" title="Search" class="button">
								<img src='<?php echo APP_PATH; ?>/assets/img/search.jpg' />
							</button>
							<br clear='all' />
						</div>
					</form>
				</div>
				
				<br clear='all' />
		    </div>
		    
		    <div id="menu">
		    	<div id="menu-wrapper" class='wrapper-width container'>
		    		<ul>
		    			<li class="active">
						    <a href="http://newsmartwave.net/magento/porto/index.php/demo5_en/">
						       <span>Home</span>
						    </a>
						</li>
						<li class="">
							<a href="http://newsmartwave.net/magento/porto/index.php/demo5_en/home-garden.html">Eletrônicos</a>
						</li>
						<li class="">
							<a href="http://newsmartwave.net/magento/porto/index.php/demo5_en/home-garden.html">Informática</a>
						</li>
						<li class="">
							<a href="http://newsmartwave.net/magento/porto/index.php/demo5_en/home-garden.html">Roupas</a>
						</li>
		    		</ul>
		    		
		    		<br clear='all' />
		    	</div>
		    </div>
	